/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:741313:
  appc.background(230);
} //_CODE_:window1:741313:

public void Pause_Clicked(GButton source, GEvent event) { //_CODE_:Pause_Button:576467:
  //Makes pause into the opposite of what it is each time the pause button is clicked
  pause = !pause;
  if(pause == true){
    Pause_Button.setText("Resume");  
    
  }
  else{
    Pause_Button.setText("Pause");
  }
  //println("Pause_Button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Pause_Button:576467:

public void Change_Number(GSlider source, GEvent event) { //_CODE_:Number_Slider:539620:
  //Get the value of the slider
  numberOfSquares = Number_Slider.getValueI();
} //_CODE_:Number_Slider:539620:

public void ColorChange(GSlider source, GEvent event) { //_CODE_:ColorSlider:229824:
  Colour1 = ColorSlider.getValueI();
} //_CODE_:ColorSlider:229824:

public void ColorChange2(GSlider source, GEvent event) { //_CODE_:ColorSlider2:643082:
  Colour2 = ColorSlider2.getValueI();
} //_CODE_:ColorSlider2:643082:

public void ColorChange3(GSlider source, GEvent event) { //_CODE_:ColorSlider3:740879:
  Colour3 = ColorSlider3.getValueI();
} //_CODE_:ColorSlider3:740879:

public void ResetClicked(GButton source, GEvent event) { //_CODE_:ResetButton:332733:
  reset();
} //_CODE_:ResetButton:332733:

public void XSliderChange(GSlider source, GEvent event) { //_CODE_:XSlider:941290:
  xcoord1 = XSlider.getValueI();
  reset(); //Calls reset function to create a new class object with a different x coordinate
} //_CODE_:XSlider:941290:

public void YSliderChange(GSlider source, GEvent event) { //_CODE_:YSlider:922285:
  ycoord1 = YSlider.getValueI();
  reset(); //Calls reset function to create a new class object with a different y coordinate
} //_CODE_:YSlider:922285:

public void SizeChange(GSlider source, GEvent event) { //_CODE_:SizeSlider:850686:
  //Side Lengths are in units of 10
  initialSize = reduce(SizeSlider.getValueI());
  reset(); //Calls reset function to create a new class object with a different side length
} //_CODE_:SizeSlider:850686:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Pause_Button = new GButton(window1, 27, 17, 80, 30);
  Pause_Button.setText("Pause");
  Pause_Button.addEventHandler(this, "Pause_Clicked");
  Number_Slider = new GSlider(window1, 306, 31, 100, 40, 10.0);
  Number_Slider.setLimits(10, 1, 10);
  Number_Slider.setNbrTicks(5);
  Number_Slider.setStickToTicks(true);
  Number_Slider.setShowTicks(true);
  Number_Slider.setNumberFormat(G4P.INTEGER, 0);
  Number_Slider.setOpaque(false);
  Number_Slider.addEventHandler(this, "Change_Number");
  label1 = new GLabel(window1, 286, 10, 134, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Number of Squares");
  label1.setOpaque(false);
  ColorSlider = new GSlider(window1, 158, 36, 100, 40, 10.0);
  ColorSlider.setLimits(125.0, 0.0, 255.0);
  ColorSlider.setNumberFormat(G4P.DECIMAL, 2);
  ColorSlider.setOpaque(false);
  ColorSlider.addEventHandler(this, "ColorChange");
  label2 = new GLabel(window1, 162, 8, 99, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Colours(RGB)");
  label2.setOpaque(false);
  ColorSlider2 = new GSlider(window1, 158, 75, 100, 40, 10.0);
  ColorSlider2.setLimits(125.0, 1.0, 255.0);
  ColorSlider2.setNumberFormat(G4P.DECIMAL, 2);
  ColorSlider2.setOpaque(false);
  ColorSlider2.addEventHandler(this, "ColorChange2");
  ColorSlider3 = new GSlider(window1, 157, 115, 100, 40, 10.0);
  ColorSlider3.setLimits(125.0, 0.0, 255.0);
  ColorSlider3.setNumberFormat(G4P.DECIMAL, 2);
  ColorSlider3.setOpaque(false);
  ColorSlider3.addEventHandler(this, "ColorChange3");
  ResetButton = new GButton(window1, 26, 66, 80, 30);
  ResetButton.setText("Reset");
  ResetButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  ResetButton.addEventHandler(this, "ResetClicked");
  XSlider = new GSlider(window1, 42, 196, 100, 40, 10.0);
  XSlider.setLimits(400.0, 200.0, 800.0);
  XSlider.setNumberFormat(G4P.DECIMAL, 2);
  XSlider.setOpaque(false);
  XSlider.addEventHandler(this, "XSliderChange");
  label3 = new GLabel(window1, 48, 176, 91, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("X Coordinates");
  label3.setOpaque(false);
  YSlider = new GSlider(window1, 165, 195, 100, 40, 10.0);
  YSlider.setLimits(400.0, 200.0, 800.0);
  YSlider.setNumberFormat(G4P.DECIMAL, 2);
  YSlider.setOpaque(false);
  YSlider.addEventHandler(this, "YSliderChange");
  label4 = new GLabel(window1, 173, 176, 86, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Y Coordinates");
  label4.setOpaque(false);
  SizeSlider = new GSlider(window1, 305, 197, 100, 40, 10.0);
  SizeSlider.setLimits(100, 50, 200);
  SizeSlider.setNumberFormat(G4P.INTEGER, 0);
  SizeSlider.setOpaque(false);
  SizeSlider.addEventHandler(this, "SizeChange");
  label5 = new GLabel(window1, 315, 177, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Size Adjuster");
  label5.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton Pause_Button; 
GSlider Number_Slider; 
GLabel label1; 
GSlider ColorSlider; 
GLabel label2; 
GSlider ColorSlider2; 
GSlider ColorSlider3; 
GButton ResetButton; 
GSlider XSlider; 
GLabel label3; 
GSlider YSlider; 
GLabel label4; 
GSlider SizeSlider; 
GLabel label5; 
